### ISSUE TITLE
issues :)

### ISSUE THREAD

**Issue by dwoggy** [Tryflle/tryfletheme#1]
sidebar and profiles not coloured ;c

**Comment by dwoggy** [comment]
nvm i dotn think theres anything u can do abt the profiles

**Comment by Tryflle** [comment]
wdym by sidebar
also i could recolor profiles but it wouldnt be ideal because nitro colors would be overriden

**Comment by Tryflle** [comment]
you mean this?
![image](https://github.com/user-attachments/assets/2ba40aae-1d49-4d12-b2a3-e967c649b349)
I can apply it but it overrides nitro colors. I usually just hide it so it isnt a problem anyways.

**Comment by dwoggy** [comment]
yeah i just think it looks kinda weird with the default colours contrasting with ur theme

**Comment by Tryflle** [comment]
Well, if you have compact profiles I personally think it looks fine
